# FROM node:16-alpine3.14 

# WORKDIR /home/app/client/

# COPY client/package*.json .

# RUN npm i

# COPY ./client .

# RUN npm run build

FROM node:16-alpine3.14

WORKDIR /usr/src/client/

COPY client/package*.json .

RUN npm i

COPY client .

EXPOSE 3000

CMD [ "npm" ,"start" ]