version: '3'
services:
  react-app:
    image: react-app-production:1.0
    ports: 
      - "80:80"
      - "443:443"
    networks:
      - mern-app
  api-server:
    image: server-prodn:1.0
    env_file: config.env
    ports:
      - "3000:3000"
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge
