variable "vpc_cidr_block" {}
variable "public_subnets" {}
variable "private_subnets" {}
variable "access_key" {}
variable "secret_key" {}
variable "my_ip" {}
variable "instance_type" {}
variable "ssh-key-loc" {}
variable "private-ssh-key-loc" {}